- hosts: all
  become: yes
  tasks:
  - name: Update the package cache
    apt:
      update_cache: yes

  - name: Upgrade all packages
    apt:
      upgrade: dist

  - name: Check if a reboot is required
    stat:
      path: /var/run/reboot-required
      get_md5: no
    register: reboot_required_file

  # - name: Reboot the server (if required)
  #   reboot:
  #     when: reboot_required_file.stat.exists == true

  - name: Remove unused packages
    apt:
      autoremove: yes

  - name: Run top in batch mode
    command: top -b -n 1
    register: top_output

  - name: Display top output
    debug:
      var: top_output.stdout

  # - name: Optimize the system
  #   apt:
  #     name: apt-utils
  #     state: present
  #   command: apt-get autoclean
  #   command: apt-get autoremove

  - name: Clear temporary storage
    command: rm -rf /tmp/*

  - name: Clear memory
    command: sync && echo 3 > /proc/sys/vm/drop_caches

  - name: Clean up Docker
    command: docker system prune --all --force

  - name: Display system status
    command: systemctl status docker
    register: docker_status

  - name: Display memory usage
    command: free -h
    register: memory_usage

  - name: Display temporary storage usage
    command: df -h /tmp
    register: tmp_storage_usage

  - name: Display output of all tasks
    debug:
      var: "{{ item }}"
    with_items:
      - docker_status.stdout
      - memory_usage.stdout
      - tmp_storage_usage.stdout