- hosts: all
  become: yes
  tasks:
  - name: Update the package cache
    apt:
      update_cache: yes

  - name: Upgrade all packages
    apt:
      upgrade: dist

  - name: Check if a reboot is required
    stat:
      path: /var/run/reboot-required
      get_md5: no
    register: reboot_required_file

  # - name: Reboot the server (if required)
  #   reboot:
  #     when: reboot_required_file.stat.exists == true

  - name: Remove unused packages
    apt:
      autoremove: yes

  # Clamav
  - name: Install ClamAV
    apt:
      name: clamav
      state: present

  - name: Install freshclam
    apt:
      name: freshclam
      state: present

  - name: Create ClamAV configuration file
    template:
      src: conf/clamav.conf.j2
      dest: /etc/clamav/clamav.conf

  - name: Start ClamAV service
    service:
      name: clamav-daemon
      state: started
      enabled: yes

  - name: Start freshclam service
    service:
      name: freshclam
      state: started
      enabled: yes

  - name: Check ClamAV service status
    command: service clamav-daemon status
    register: clamav_status

  - name: Display ClamAV service status
    debug:
      var: clamav_status.stdout
        
  # - name: Scan for viruses and malware
  #   apt:
  #     name: clamav
  #     state: present
  #     only_if: '! dpkg -l | grep -q "^ii clamav"'

  # - name: Monitor the system resources
  #   command: top

  # - name: Monitor the system resources - Quit
  #   command: q

  # - name: Optimize the system
  #   apt:
  #     name: apt-utils
  #     state: present
  #   command: apt-get autoclean
  #   command: apt-get autoremove