- hosts: all
  become: yes
  tasks:
  - name: Update the package cache
    apt:
      update_cache: yes

  - name: Upgrade all packages
    apt:
      upgrade: dist

  - name: Check if a reboot is required
    stat:
      path: /var/run/reboot-required
      get_md5: no
    register: reboot_required_file

  - name: Reboot the server (if required)
    reboot:
      when: reboot_required_file.stat.exists == true

  - name: Remove unused packages
    apt:
      autoremove: yes

  # journalctl
  - name: Run journalctl and quit
    command: journalctl
    become: yes
    register: journalctl_output

  - name: Display journalctl output
    debug:
      var: journalctl_output.stdout

  # Backup PC
  - name: Install BackupPC
    apt:
      name: backuppc
      state: present

  - name: Create BackupPC configuration file
    template:
      src: conf/backuppc.conf.j2
      dest: /etc/backuppc/backuppc.conf

  - name: Start BackupPC service
    service:
      name: backuppc
      state: started
      enabled: yes

  - name: Restart BackupPC service
    service:
      name: backuppc
      state: restarted

  - name: Check BackupPC service status
    command: service backuppc status
    register: backuppc_status

  - name: Display BackupPC service status
    debug:
      var: backuppc_status.stdout

  # - name: Check the system logs
  #   command: journalctl

  # - name: Back up the system
  #   apt:
  #     name: backuppc
  #     state: present
  #     only_if: '! dpkg -l | grep -q "^ii backuppc"'

  # - name: Scan for viruses and malware
  #   apt:
  #     name: clamav
  #     state: present
  #     only_if: '! dpkg -l | grep -q "^ii clamav"'

  # - name: Monitor the system resources
  #   command: top

  # - name: Monitor the system resources - Quit
  #   command: q

  # - name: Optimize the system
  #   apt:
  #     name: apt-utils
  #     state: present
  #   command: apt-get autoclean
  #   command: apt-get autoremove